name: Tests

on: [push, pull_request]

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2022, macos-11]
        # See https://nodejs.org/en/about/releases/ for latest LTS information.
        node: [16] # Active LTS
        include:
          # Also test Maintenance LTS, but just one OS should give us sufficient
          # coverage.
          - node: 14
            os: ubuntu-20.04

    timeout-minutes: 15
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - run: npm ci
      - run: npm run build
      - run: npm test

  lint-and-format:
    timeout-minutes: 5
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - run: npm ci
      - run: npm run lint
      - run: npm run format:check
